### ISSUE TITLE
can player work with http:// streams?

### ISSUE THREAD

**Issue by inglesuniversal** [mk2box/kanal77-radio-player#1]
shoutcast is giving errors on chrome with http ONLY links.

How can this be solved?

thanks and congratulations for your awesome work.

**Comment by mk2box** [comment]
All browsers don`t support shoutcast without SSL.
You need to install SSL on your shotcast server to be able to play

Here is some help: [https://help.shoutcast.com/hc/en-us/articles/360003410613-How-to-setup-SSL-for-your-Shoutcast-Server-Software-](https://help.shoutcast.com/hc/en-us/articles/360003410613-How-to-setup-SSL-for-your-Shoutcast-Server-Software-)
